### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by ichsansandy** [ichsansandy/dishdiscovery-capstone-microverse#21]
- Link to the github [project](https://github.com/ichsansandy/dishdiscovery-capstone-microverse/projects/1)
- Our group consist of 2 people

**Comment by Olamarx** [comment]
> * Link to the github [project](https://github.com/ichsansandy/dishdiscovery-capstone-microverse/projects/1)
> * Our group consist of 2 people

Hi Team, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>
## Highlights
- Equal distribution ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] I will implore you to assign each task to team members so that they can know what they are working on and for organization purposes.
![image](https://github.com/microhass/javascript-capstone-2/assets/86200356/5d521c5a-f191-4d4b-9c40-66bb02a1ed8c)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ichsansandy** [comment]
Re-assigning issue with all of the members of the team

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @ichsansandy & @abdozayan12  👋, 

**Your Kanban board is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Fair distribution of activities ✔
- All cards are properly assigned to team members ✔
- Proper template used ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
